-- Private profile avatar and cover media.
-- Only durable Storage paths are persisted. Signed URLs are generated by the application when read.

alter table public.profiles
  add column avatar_path text check (
    avatar_path is null
    or (char_length(avatar_path) between 1 and 500 and avatar_path like user_id::text || '/avatar/%')
  ),
  add column cover_path text check (
    cover_path is null
    or (char_length(cover_path) between 1 and 500 and cover_path like user_id::text || '/cover/%')
  );

-- The existing profile UPDATE policy still limits rows to auth.uid(). Column grants prevent other fields changing.
grant update (avatar_path, cover_path) on public.profiles to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('profile-media', 'profile-media', false, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
  set public = false, file_size_limit = 5242880, allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

-- Read access deliberately mirrors profiles_select exactly: self, shared room, or a friendship/request.
create policy profile_media_objects_read on storage.objects for select to authenticated
  using (
    bucket_id = 'profile-media'
    and (
      public.try_uuid((storage.foldername(name))[1]) = auth.uid()
      or public.shares_room_with(public.try_uuid((storage.foldername(name))[1]))
      or public.has_friendship_with(public.try_uuid((storage.foldername(name))[1]))
    )
  );

-- Every upload uses a fresh object name. There is intentionally no UPDATE policy, so even an owner cannot
-- overwrite an existing object in place; the profile row is changed first, then the old object is removed.
create policy profile_media_objects_insert on storage.objects for insert to authenticated
  with check (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = auth.uid()::text
    and (storage.foldername(name))[2] in ('avatar', 'cover')
  );

create policy profile_media_objects_delete on storage.objects for delete to authenticated
  using (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
